Update cicd.yaml

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -152,4 +152,13 @@ jobs:
             fi
             cd capstone_project
             docker-compose -f ./compose.yaml pull
+             # Run test container (inside Docker) first
+            docker-compose -f ./compose.yaml up --abort-on-container-exit tests
+  
+            # Capture exit code of tests
+            TEST_EXIT_CODE=$?
+            if [ $TEST_EXIT_CODE -ne 0 ]; then
+              echo "Tests failed! Deployment aborted."
+              exit 1
+            fi
             docker-compose -f ./compose.yaml up -d --remove-orphans
